version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/your_database_name
  db:
    image: postgres
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
